apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-02-13T15:06:18Z"
  generateName: reflector-6dccc8558b-
  labels:
    app.kubernetes.io/instance: reflector
    app.kubernetes.io/name: reflector
    pod-template-hash: 6dccc8558b
  name: reflector-6dccc8558b-zxlpn
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: reflector-6dccc8558b
    uid: b553932c-e9a0-4fae-8e91-b4d410cfc6cb
  resourceVersion: "17697024082"
  uid: 49f3f3d6-450a-4b70-8c69-eb1ba9d3ba2b
spec:
  containers:
  - env:
    - name: ES_Serilog__MinimumLevel__Default
      value: Information
    - name: ES_Reflector__Watcher__Timeout
    - name: ES_Reflector__Kubernetes__SkipTlsVerify
      value: "false"
    image: emberstack/kubernetes-reflector:7.1.238
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: http
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: reflector
    ports:
    - containerPort: 25080
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: http
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 1000
    startupProbe:
      failureThreshold: 10
      httpGet:
        path: /healthz
        port: http
        scheme: HTTP
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5dbvj
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: scw-dev-daplay-dev-daplay-cluster-pool-0634fce
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 2000
  serviceAccount: reflector
  serviceAccountName: reflector
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-5dbvj
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-02-13T15:07:31Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-02-13T15:07:51Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-02-13T15:07:51Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-02-13T15:07:19Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://7ebaa115859593241165db2663639c1b83f5eebe5eef56eb2baa31abf3382691
    image: docker.io/emberstack/kubernetes-reflector:7.1.238
    imageID: docker.io/emberstack/kubernetes-reflector@sha256:24e9cafc935689db6fcf637dc656f015e3d683875f80995aaa0ea0fc0e27ab7a
    lastState: {}
    name: reflector
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-02-13T15:07:37Z"
  hostIP: 10.40.0.3
  phase: Running
  podIP: 100.64.0.53
  podIPs:
  - ip: 100.64.0.53
  qosClass: BestEffort
  startTime: "2024-02-13T15:07:31Z"
