### GET request to example server
GET https://examples.http-client.intellij.net/get$END$
    ?generated-in=GoLand

###
### Send POST request with json body
POST http://localhost:8087/users
Content-Type: application/json

{
  "first_name": "aalysher",
  "last_name": "dev",
  "email": "dev@gmail.com",
  "age": 30
}

<> 2024-05-25T153631.200.json

###

###

GET http://localhost:3000/organizations/

<> 2024-07-01T181944.200.html


###

GET http://localhost:3000/api/auth/session

<> 2024-07-01T182917.401.json
<> 2024-07-01T182245.401.json