apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"argocd.argoproj.io/instance":"overlord"},"name":"overlord","namespace":"overlord"},"spec":{"ports":[{"name":"http","port":5000,"targetPort":"http"},{"name":"grpc","port":7000,"targetPort":"grpc"}],"selector":{"app":"overlord"}}}
  creationTimestamp: "2024-04-23T11:36:09Z"
  labels:
    argocd.argoproj.io/instance: overlord
  name: overlord
  namespace: overlord
  resourceVersion: "19165017357"
  uid: d649dd0e-41a9-4a6e-b427-9e9befcc623a
spec:
  clusterIP: 10.38.102.34
  clusterIPs:
  - 10.38.102.34
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: http
  - name: grpc
    port: 7000
    protocol: TCP
    targetPort: grpc
  selector:
    app: overlord
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
